name: innolab
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  
  # UTILITY PACKAGES
  http: ^1.6.0
  intl: ^0.20.2
  logger: ^1.1.0
  url_launcher: ^6.1.7 

  # FIREBASE PACKAGES 
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0 
  cloud_firestore: ^6.1.3

  # ICONS
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8



  # STATE MANAGEMENT
  get: ^4.7.3
  get_storage: ^2.0.3


  # PRODUCT SPECIFIC PACKAGES

  google_fonts: ^8.0.2
  provider: ^6.0.5
  flutter_svg: ^2.2.4
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  file_picker: ^10.3.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

  
  
  # LOCAL ASSETS
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
